// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;

/// @title Groth16 Verifier for Repute Reputation Circuit
/// @notice Auto-generated structure — production version will be generated by snarkjs.
///         This is a placeholder with the correct interface. Run `npm run circuit:compile`
///         to generate the real verifier from the compiled circuit.
/// @dev Verifies Groth16 proofs with 5 public inputs:
///      [0] nullifierHash
///      [1] minBalance
///      [2] minTxCount
///      [3] minWalletAge
///      [4] commitmentHash

contract Groth16Verifier {

    // Scalar field size
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct Proof {
        uint256[2] a;       // G1 point
        uint256[2][2] b;    // G2 point
        uint256[2] c;       // G1 point
    }

    // Verification key components (populated after trusted setup)
    // These are placeholder values — the real ones are generated by snarkjs
    uint256[2] internal alfa1;
    uint256[2][2] internal beta2;
    uint256[2][2] internal gamma2;
    uint256[2][2] internal delta2;
    uint256[2][] internal IC; // nPublic + 1 elements

    bool public initialized;
    address public owner;

    event VerificationKeySet();

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /// @notice Set verification key parameters (called once after circuit compilation)
    /// @dev In production, snarkjs generates a contract with these hardcoded.
    ///      This function allows updating them without redeploying.
    function setVerificationKey(
        uint256[2] memory _alfa1,
        uint256[2][2] memory _beta2,
        uint256[2][2] memory _gamma2,
        uint256[2][2] memory _delta2,
        uint256[2][] memory _IC
    ) external onlyOwner {
        require(_IC.length == 6, "IC length must be nPublic+1 = 6");
        alfa1 = _alfa1;
        beta2 = _beta2;
        gamma2 = _gamma2;
        delta2 = _delta2;

        // Clear and set IC
        delete IC;
        for (uint256 i = 0; i < _IC.length; i++) {
            IC.push(_IC[i]);
        }

        initialized = true;
        emit VerificationKeySet();
    }

    /// @notice Verify a Groth16 proof
    /// @param _pA Proof element A (G1)
    /// @param _pB Proof element B (G2)
    /// @param _pC Proof element C (G1)
    /// @param _pubSignals Array of 5 public signals
    /// @return True if the proof is valid
    function verifyProof(
        uint256[2] memory _pA,
        uint256[2][2] memory _pB,
        uint256[2] memory _pC,
        uint256[5] memory _pubSignals
    ) public view returns (bool) {
        require(initialized, "Verification key not set");

        // Check public signals are in field
        for (uint256 i = 0; i < 5; i++) {
            require(_pubSignals[i] < PRIME_Q, "Public signal out of range");
        }

        // Compute the linear combination vk_x
        uint256[2] memory vk_x = IC[0];
        for (uint256 i = 0; i < 5; i++) {
            (uint256 rx, uint256 ry) = _scalarMul(IC[i + 1], _pubSignals[i]);
            (vk_x[0], vk_x[1]) = _pointAdd(vk_x[0], vk_x[1], rx, ry);
        }

        // Pairing check: e(-A, B) * e(alfa1, beta2) * e(vk_x, gamma2) * e(C, delta2) == 1
        return _pairingCheck(
            _pA, _pB,
            alfa1, beta2,
            [vk_x[0], vk_x[1]], gamma2,
            _pC, delta2
        );
    }

    /// @dev Elliptic curve scalar multiplication via precompile
    function _scalarMul(uint256[2] memory p, uint256 s) internal view returns (uint256, uint256) {
        uint256[3] memory input;
        input[0] = p[0];
        input[1] = p[1];
        input[2] = s;
        uint256[2] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 7, input, 0x60, result, 0x40)
        }
        require(success, "EC scalar mul failed");
        return (result[0], result[1]);
    }

    /// @dev Elliptic curve point addition via precompile
    function _pointAdd(uint256 x1, uint256 y1, uint256 x2, uint256 y2) internal view returns (uint256, uint256) {
        uint256[4] memory input;
        input[0] = x1;
        input[1] = y1;
        input[2] = x2;
        input[3] = y2;
        uint256[2] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 6, input, 0x80, result, 0x40)
        }
        require(success, "EC point add failed");
        return (result[0], result[1]);
    }

    /// @dev Pairing check via precompile (bn128)
    function _pairingCheck(
        uint256[2] memory a1, uint256[2][2] memory b1,
        uint256[2] memory a2, uint256[2][2] memory b2,
        uint256[2] memory a3, uint256[2][2] memory b3,
        uint256[2] memory a4, uint256[2][2] memory b4
    ) internal view returns (bool) {
        uint256[24] memory input;

        // Negate a1 for the pairing equation
        input[0] = a1[0];
        input[1] = (PRIME_Q - a1[1]) % PRIME_Q;
        input[2] = b1[0][1]; // Note: G2 point coords are swapped in EVM
        input[3] = b1[0][0];
        input[4] = b1[1][1];
        input[5] = b1[1][0];

        input[6] = a2[0];
        input[7] = a2[1];
        input[8] = b2[0][1];
        input[9] = b2[0][0];
        input[10] = b2[1][1];
        input[11] = b2[1][0];

        input[12] = a3[0];
        input[13] = a3[1];
        input[14] = b3[0][1];
        input[15] = b3[0][0];
        input[16] = b3[1][1];
        input[17] = b3[1][0];

        input[18] = a4[0];
        input[19] = a4[1];
        input[20] = b4[0][1];
        input[21] = b4[0][0];
        input[22] = b4[1][1];
        input[23] = b4[1][0];

        uint256[1] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 8, input, 0x300, result, 0x20)
        }
        require(success, "Pairing check failed");
        return result[0] == 1;
    }
}
